import Navbar from "@/components/Navbar";
import "./globals.css";
import "react-datepicker/dist/react-datepicker.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import Loading from "./loading";
import AuthContextProvider from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BookTable",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100 min-h-screen`}>
        <AuthContextProvider>
          <main className="max-w-screen-2xl m-auto bg-white">
            <Navbar />
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </main>
        </AuthContextProvider>
      </body>
    </html>
  );
}
